Eindejaarsproject/Eindejaarproject.Web/Areas/Customer/Controllers/QuotationController.cs
using Eindejaarproject.Web.Controllers;
using Eindejaarsproject.DA.IRepositories;
using Eindejaarsproject.Services.IServices;
using Microsoft.AspNet.Identity;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace Eindejaarproject.Web.Areas.Customer.Controllers
{
    [Authorize(Roles = "Administrator, Customer")]
    public class QuotationController : BaseController
    {
        #region Constructor
        private readonly IQuotationRepository quotationRepository;

        private readonly IUserRepository _userRepository;
        private readonly IPDFService _pdfService;
        private readonly IMailService _mailService;
        public QuotationController(IQuotationRepository quotationRepository, IPDFService pdfService, IMailService mailService, IUserRepository userRepository)
        {
            this.quotationRepository = quotationRepository;
            this._pdfService = pdfService;
            this._mailService = mailService;
            this._userRepository = userRepository;
        }

        #endregion

        [HttpGet]
        public async Task<ActionResult> List(int projectId)
        {
            var model = await quotationRepository.GetQuotationsForList(null,projectId);
            return View(model);
        }


        [HttpGet]
        public async Task<ActionResult> AcceptQuotation(int id)
        {
            var customerId = User.Identity.GetUserId();

            var result = await quotationRepository.AcceptQuotation(id, customerId);
            if(!string.IsNullOrEmpty(result))
            {
                var details = await _userRepository.GetUserDetails(result);


                if(details != null)
                {
                    _mailService.SendMail(string.Format("{0} {1}", details.FirstName, details.LastName), new string[] { details.Email }, "Quoatation accepted", "One of your quotation has been accepted.");
                }

                AddDataToTempData("succes", "Your quotation has been accepted.");
            }
            else
            {
                AddDataToTempData("danger", "An error occured while saving. Pleas try again.");
            }

            return RedirectToAction("List", "Project");
           
        }


        [HttpGet]
        public async Task<ActionResult> DownloadQuotation(int id, bool isInvoice = false)
        {
            var quotation = await quotationRepository.GetQuotationDetails(id);


            if(quotation == null)
            {

                return RedirectToAction("List", new { projectId = id });
                
            }

            MemoryStream file = _pdfService.CreateQuotation(quotation, isInvoice);



            Response.ContentType = "application/pdf";
            Response.AddHeader("Content-Disposition", string.Format("attachment;filename={0}-{1}.pdf", isInvoice ? "invoice" : "quatation",  id));
            Response.BinaryWrite(file.ToArray());
            return View();
        }
    }
}

Eindejaarsproject/Eindejaarproject.Web/Areas/Freelancer/Controllers/QuotationController.cs
using Eindejaarproject.Web.Controllers;
using Eindejaarsproject.DA.IRepositories;
using Eindejaarsproject.DA.ViewModels;
using Eindejaarsproject.Services.IServices;
using Microsoft.AspNet.Identity;
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace Eindejaarproject.Web.Areas.Freelancer.Controllers
{
    [Authorize(Roles = "Administrator, Freelancer")]
    public class QuotationController : BaseController
    {

        #region Constructor

        private readonly IQuotationRepository quotationRepository;
        private readonly IMailService _mailService;
        private readonly IUserRepository _userRepository;

        public QuotationController(IQuotationRepository quotationRepository, IMailService mailService, IUserRepository userRepository)
        {
            this.quotationRepository = quotationRepository;
            this._mailService = mailService;
            this._userRepository = userRepository;
        }

        #endregion


        [HttpGet]
        public async Task<ActionResult> List()
        {
            var freelancerId = User.Identity.GetUserId();
            var model = await quotationRepository.GetQuotationsForList(freelancerId);

            return View(model);
        }


        [HttpGet]
        [ValidateInput(false)]
        public async Task<ActionResult> Create(int projectId)
        {
            UpsertQuotationViewModel model = new UpsertQuotationViewModel();
            model.ProjectId = projectId;
            model.Quotations = await quotationRepository.GetQuotationsForList(null, projectId);

            return View(model);
        }

        [HttpPost]
        [ValidateInput(false)]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create(UpsertQuotationViewModel model)
        {
            if (ModelState.IsValid)
            {
                model.AspNetUserId = User.Identity.GetUserId();
                model.ExpirationDate = Convert.ToDateTime(model.ExpirationDateString, new CultureInfo("nl-BE"));
                var userDetails = await  _userRepository.GetUserDetailsByProjectId(model.ProjectId);


                model.FirstName = userDetails.FirstName;
                model.LastName = userDetails.LastName;
                model.Address = userDetails.Address;


                var result = await quotationRepository.UpsertQuotation(model);

                //UserDetailsViewModel userDetails = await _userRepository.GetUserDetailsByProjectId(model.ProjectId);
                _mailService.SendMail(string.Format("{0} {1}", userDetails.FirstName, userDetails.LastName), new string[] { userDetails.Email }, "New Quotation", "There is a new quotation for one of your projects.");

                AddDataToTempData("succes", "Your quotation has been created");
                return RedirectToAction("List", "Project");

            }

            model.Quotations = await quotationRepository.GetQuotationsForList(null, model.ProjectId);
            AddDataToTempData("danger", "Error");
            return View(model);
        }



    }
}

Eindejaarsproject/Eindejaarproject.Web/Areas/Freelancer/Views/Quotation/Create.cshtml
@model Eindejaarsproject.DA.ViewModels.UpsertQuotationViewModel
@using Eindejaarsproject.DA.Resources;

@{
    ViewBag.Title = Global.Create;
}


<h2>@Global.Create</h2>
<div class="row">
    @using (Html.BeginForm("Create", "Quotation", FormMethod.Post, new { @class = "form-horizontal", @novalidate = "novalidate" }))
    {

        @Html.AntiForgeryToken()
        @Html.HiddenFor(m => m.ProjectId)

        <div class="form-group">
            @Html.LabelFor(m => m.PriceExclTax, new { @class = "control-label col-sm-3  col-md-2" })
            <div class="col-sm-9 col-md-10">
                <div class="input-group">
                    <span class="input-group-addon"><i class="fa fa-eur"></i></span>
                    @Html.TextBoxFor(m => m.PriceExclTax, new { @class = "form-control", Type = "number", @min = "0", @data_val = "false" })
                </div>
                @Html.ValidationMessageFor(m => m.PriceExclTax, null, new { @class = "text-danger" })
            </div>
        </div>
            <div class="form-group">
                @Html.LabelFor(m => m.DeliveryPeriodExpressedInDays, new { @class = "control-label col-sm-3  col-md-2" })
                <div class="col-sm-9 col-md-10 ">
                    <div class="input-group">
                        <span class="input-group-addon"><i class="fa fa-calendar"></i></span>
                        @Html.TextBoxFor(m => m.DeliveryPeriodExpressedInDays, new { @class = "form-control", Type = "number", @min = "0" })
                        <span class="input-group-addon lead">days after quotation acceptation</span>
                    </div>
                    @Html.ValidationMessageFor(m => m.DeliveryPeriodExpressedInDays, null, new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group">
                @Html.LabelFor(m => m.ExpirationDateString, new { @class = "control-label col-sm-3 col-md-2" })
                <div class="col-sm-9 col-md-10">
                    <div class="input-group date">
                        <span class="input-group-addon"><i class="fa fa-calendar"></i></span>
                        @Html.TextBoxFor(m => m.ExpirationDateString, new { @class = "form-control", placeholder = "DD-MM-YYYY" })

                    </div>
                    @Html.ValidationMessageFor(m => m.ExpirationDateString, null, new { @class = "text-danger" })
                    @*@Html.ValidationMessage("DesiredDeadlineIsLessOrEqualThanNow", new { @class = "text-danger" })*@
                </div>
            </div>

            <button type="submit" class="btn btn-success pull-right">@Global.Create</button>
    }
</div>
<div class="row m-t-m">
    @Html.Partial("_QuotationForListTable", Model.Quotations)
</div>

Eindejaarsproject/Eindejaarproject.Web/Areas/Freelancer/Views/Quotation/List.cshtml
@model List<Eindejaarsproject.DA.ViewModels.QuotationForListViewModel>
@using Eindejaarsproject.DA.Resources 
@{
    ViewBag.Title = Global.Quotations;
}

<h2>@ViewBag.Title</h2>

@Html.Partial("_QuotationForListTable", Model)